openai:
  conversation: False
  model: gpt-3.5-turbo

  # 可使用的模型：
  # davinci-instruct-beta-v3
  # text-davinci-003
  # text-davinci-002
  # text-davinci-001
  # text-curie-001
  # text-babbage-001
  # text-ada-001

  # code-davinci-002
  # code-cushman-001

  # text-similarity-ada-001
  # text-similarity-babbage-001
  # text-similarity-curie-001
  # text-similarity-davinci-001

  # text-search-ada-doc-001
  # text-search-ada-query-001
  # text-search-babbage-doc-001
  # text-search-babbage-query-001
  # text-search-curie-doc-001
  # text-search-curie-query-001
  # text-search-davinci-doc-001
  # text-search-davinci-query-001
    
  # code-search-ada-code-001
  # code-search-ada-text-001
  # code-search-babbage-code-001
  # code-search-babbage-text-001
